version: '3.2'
networks:
  private:
  public:
    external:
      name: traefik_webgateway
volumes:
  yarn:
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    networks:
      - private
  web:
    image: node:11-alpine
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}-web
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.localhost
      - traefik.port=3000
    networks:
      - public
      - private
    user: node
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
      - yarn:/home/node/.cache
      - ${PWD}:/var/www
    working_dir: /var/www
    command: "yarn run start"
