version: '3.2'
networks:
  private:
  public:
    external:
      name: traefik_webgateway
volumes:
  yarn:
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    networks:
      - private
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    environment:
        - CONTAINERS=1
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}-api
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.localhost;PathPrefixStrip:/api
      - traefik.port=2375
    networks:
      - public
      - private
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID:-0}
    command: "yarn run start"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}-web
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.localhost
      - traefik.port=8080
    networks:
      - public
      - private
    user: node
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
      - yarn:/home/node/.cache
      - ${PWD}:/var/www
    working_dir: /var/www
