FROM jtreminio/php-nginx:7.3

ENV APP_ENV=dev
ENV APP_HOME=/var/www

# Custom user and group ID
ARG USER_ID
ARG GROUP_ID
ARG DOCKER_GROUP_ID
RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
  userdel -f www-data &&\
  if getent group www-data ; then groupdel www-data; fi &&\
  groupadd -g ${GROUP_ID} www-data &&\
  useradd -l -u ${USER_ID} -g www-data www-data &&\
  chown --changes --no-dereference --recursive --from=33:33 ${USER_ID}:${GROUP_ID} \
    /.composer \
    /var/run/php-fpm \
    /var/lib/php/sessions \
    /var/lib/nginx \
    /var/cache/nginx \
    /var/run/nginx \
;fi

RUN groupadd -for -g ${DOCKER_GROUP_ID} docker &&\
    usermod -aG docker www-data

WORKDIR ${APP_HOME}
